// my-vue-app/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'

import Animation from './components/Animation/index.vue'
import counterWrapper from 'my-react-app-1/counterWrapper'

const divRef = ref()

onMounted(() => {
  counterWrapper(divRef.value)
})
</script>

<template>
  <main className="flex h-screen flex-col items-center justify-center gap-8 bg-zinc-900 text-white">
    <h1 className="text-3xl font-bold">My Vue App</h1>
    
    <Animation />

    <div ref="divRef"></div>
  </main>
</template>

// my-react-app-2/src/App.tsx
import { useRef, useEffect } from "react";
import { Counter } from "my-react-app-1/Counter";
import animationWrapper from "my-vue-app/animationWrapper";

import "./index.css";

function App() {
  const animationRef = useRef<HTMLElement>(null);

  useEffect(() => {
    animationWrapper(animationRef.current);
  }, []);

  return (
    <main className="flex h-screen flex-col items-center justify-center gap-8 bg-zinc-900 text-white">
      <h1 className="text-3xl font-bold">My React App 2</h1>

      <Counter incrementBy={10} initialValue={5} />

      <div ref={animationRef} />
    </main>
  );
}

export default App;
